### ISSUE TITLE
'sequential_sleeps' statistic breaks statistics menu for vanilla clients

### ISSUE THREAD

**Issue by tesseract-two** [z3roco01/Inverse-Phantoms#1]
Vanilla clients get disconnected from the server upon opening the statistics menu when they have an entry for 'minecraft:sequential_sleeps'.

Unfortunately it looks like that statistic is how the mod counts sleeps, and I don't know if there's a different way to do that.

The mod still functions server side, just vanilla clients can't view statistics.

**Comment by z3roco01** [comment]
i had taken a break from modding but ill look in to this now :3

**Comment by z3roco01** [comment]
srry i got busy then forgot abt this, but its fixed now !

**Comment by tesseract-two** [comment]
No worries, I was gone all summer too, thanks for fixing this!
